export const SKU_MASTER_LIST = [
    'MamyPoko Pants Standard S 4-8kg',
    'MamyPoko Pants Standard M 7-12kg',
    'MamyPoko Pants Standard L 9-14kg',
    'MamyPoko Pants Standard XL 12-17kg',
    'MamyPoko Pants Standard XXL 15-25kg',
    'MamyPoko Pants Premium Care S 4-8kg',
    'MamyPoko Pants Premium Care M 7-12kg',
    'MamyPoko Pants Premium Care L 9-14kg',
    'MamyPoko Pants Premium Care XL 12-17kg',
    'MamyPoko Pants Premium Care XXL 15-25kg',
    'MamyPoko Pants Extra Absorb S 4-8kg',
    'MamyPoko Pants Extra Absorb M 7-12kg',
    'MamyPoko Pants Extra Absorb L 9-14kg',
    'MamyPoko Pants Extra Absorb XL 12-17kg',
    'MamyPoko Pants Extra Absorb XXL 15-25kg',
    'Sofy Antibacterial S 230mm',
    'Sofy Antibacterial XL 300mm',
    'Sofy Cool XL 300mm',
    'Sofy Bodyfit Comfort S 230mm',
    'Lifree Adult Diapers M-L',
    'Lifree Adult Diapers L-XL'
];
